name: cctp-dst
description: Indexing circle etheruem cctp contracts
startBlock: 25114705
userId: google-oauth2%7C113106604109449522744
projectId: 9b8821f7-0942-4afa-b739-6d2560166cb2
network: Avalanche
user: prady-cctp
schema:
  file: ./studio.schema.ts
execution: parallel
Resources:
  - Name: counts
    Type: api
    Slug: count
    Handler: src/apis/counts.countHandler
  - Name: flows
    Type: api
    Slug: flow
    Handler: src/apis/flows.flowHandler
  - Name: users
    Type: api
    Slug: top/users
    Handler: src/apis/user.userHandler
