// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { Document } from "@blockflow-labs/utils";

export class Swap {
  static entity = "Swap";
  static schema = {
    id: { type: "String", index: true },
    caller: "String",
    receiver: "String",
    tokenIn: "String",
    tokenOut: "String",
    amountIn: "String",
    amountOut: "String",
    block_timestamp: "string",
    transaction_hash: "string",
    transaction_index: "string",
    log_index: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class Deposit {
  static entity = "Deposit";
  static schema = {
    id: { type: "String", index: true },
    caller: "String",
    receiver: "String",
    lpAmount: "String",
    block_timestamp: "string",
    transaction_hash: "string",
    transaction_index: "string",
    log_index: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class RemoveLiquidity {
  static entity = "RemoveLiquidity";
  static schema = {
    id: { type: "String", index: true },
    caller: "String",
    receiver: "String",
    type: "String",
    lpAmount: "String",
    addressToken: "String",
    amount: "String",
    block_timestamp: "string",
    transaction_hash: "string",
    transaction_index: "string",
    log_index: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

import { String } from "@blockflow-labs/utils";

export interface ISwap extends Document {
  id: String;

  caller: String;
  receiver: String;

  tokenIn: String;
  tokenOut: String;

  amountIn: String;
  amountOut: String;

  block_timestamp: string;
  transaction_hash: string;
  transaction_index: string;
  log_index: string;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface IDeposit extends Document {
  id: String;

  caller: String;
  receiver: String;

  lpAmount: String;

  block_timestamp: string;
  transaction_hash: string;
  transaction_index: string;
  log_index: string;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface IRemoveLiquidity extends Document {
  id: String;

  caller: String;
  receiver: String;
  type: String;

  lpAmount: String;

  addressToken: String;

  amount: String;

  block_timestamp: string;
  transaction_hash: string;
  transaction_index: string;
  log_index: string;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}
